
ieee80211-rtl-objs := ieee80211_softmac.o \
                      ieee80211_rx.o \
                      ieee80211_tx.o \
                      ieee80211_wx.o \
                      ieee80211_module.o \
                      ieee80211_softmac_wx.o

obj-$(CONFIG_REALTEK_PCI_RTL8185)  += ieee80211-rtl.o ieee80211_crypt.o
obj-$(CONFIG_REALTEK_PCI_RTL8185)  += ieee80211_crypt_tkip.o ieee80211_crypt_ccmp.o ieee80211_crypt_wep.o
