# this is for the realtek's 802.11 devices
obj-$(CONFIG_REALTEK_USB_RTL8187)       += rtl8187/

obj-$(CONFIG_REALTEK_USB_RTL8709)	    += rtl8709/

obj-$(CONFIG_REALTEK_USB_RTL8192)	    += 11n8709/

obj-$(CONFIG_REALTEK_USB_RTL8191SU)	    += rtl8191su/

obj-$(CONFIG_REALTEK_PCI_RTL8185)       += rtl8185/

obj-$(CONFIG_REALTEK_PCI_RTL8190)       += rtl8190/

