#!/bin/bash

# Select NIC type
card=RTL8192su

SYSTEM=`uname -r|cut -d. -f1,2`

if [ $SYSTEM = 2.4 ]
then
cd rtllib
#insmod rtllib_crypt-rsl.o
#insmod crypto-rsl.o
#insmod michael_mic-rsl.o
#insmod aes-rsl.o
#insmod rtllib_crypt_wep-rsl.o
#insmod rtllib_crypt_tkip-rsl.o
#insmod rtllib_crypt_ccmp-rsl.o
#insmod rtllib-rsl.o

#insmod 
case "$card" in
        "RTL8192u")
        cd ../HAL/rtl8192u;
	insmod r8192_usb.o;;
        "RTL8192su")
        cd ../HAL/rtl8192u;
	insmod r8192s_usb.o;;
        "RTL8190p")
        cd ../HAL/rtl8192;
        insmod r8190_pci.o;;
        "RTL8192e")
        cd ../HAL/rtl8192;
        insmod r8192e_pci.o;;
	"RTL8192se")
	cd ../HAL/rtl8192;
	insmod r8192se_pci.o;;
	"RTL8191se_Mesh")
	cd ../HAL/rtl8192;
	insmod r8192se_pci_mesh.o;;
	"RTL8192ce")
	cd ../HAL/rtl8192;
	insmod r8192ce_pci.o;;
        *)
        echo "Unknown NIC type"
	;;
esac

else
cp RadioPower.sh /etc/acpi/events
cd rtllib/
#insmod rtllib_crypt-rsl.ko
#insmod rtllib_crypt_wep-rsl.ko
#insmod rtllib_crypt_tkip-rsl.ko
#insmod rtllib_crypt_ccmp-rsl.ko
#insmod rtllib-rsl.ko

#insmod
case "$card" in
        "RTL8192u")
        cd ../HAL/rtl8192u;
	insmod r8192_usb.ko;;
        "RTL8192su")
        cd ../HAL/rtl8192u;
	insmod r8192s_usb.ko;;
        "RTL8190p")
        cd ../HAL/rtl8192;
        insmod r8190_pci.ko;;
        "RTL8192e")
        cd ../HAL/rtl8192;
        insmod r8192e_pci.ko;;
	"RTL8192se")
	cd ../HAL/rtl8192;
	insmod r8192se_pci.ko;;
	"RTL8191se_Mesh")
	cd ../HAL/rtl8192;
	insmod r8192se_pci_mesh.ko;;
	"RTL8192ce")
	cd ../HAL/rtl8192;
	insmod r8192ce_pci.ko;;
        *)
        echo "Unknown NIC type"
	;;
esac
fi

cd ../..
#ifconfig wlan0 up
