#!/bin/bash

# Select NIC type
card=RTL8192u

ifconfig wlan0 down
SYSTEM=`uname -r|cut -d. -f1,2`

if [ $SYSTEM = 2.4 ]
then
#rmmod 
case "$card" in
        "RTL8192u")
        rmmod r8192_usb;;
        "RTL8190p")
        rmmod r8190_pci;;
        "RTL8192e")
        rmmod r8192_pci;;
        *)
        echo "Unknown NIC type"
	;;
esac
rmmod ieee80211-rsl
rmmod ieee80211_crypt_ccmp-rsl
rmmod ieee80211_crypt_tkip-rsl
rmmod ieee80211_crypt_wep-rsl
rmmod aes-rsl
rmmod michael_mic-rsl
rmmod crypto-rsl
rmmod ieee80211_crypt-rsl
else
#rmmod 
case "$card" in
        "RTL8192u")
        rmmod r8192_usb.ko;;
        "RTL8190p")
        rmmod r8190_pci.ko;;
        "RTL8192e")
        rmmod r8192_pci.ko;;
        *)
        echo "Unknown NIC type"
	break;;
esac
rmmod ieee80211-rsl.ko
rmmod ieee80211_crypt_ccmp-rsl.ko
rmmod ieee80211_crypt_tkip-rsl.ko
rmmod ieee80211_crypt_wep-rsl.ko
rmmod ieee80211_crypt-rsl.ko
fi
