r8180-objs := r8180_core.o \
              r8180_sa2400.o \
              r8180_93cx6.o \
              r8180_wx.o \
              r8180_max2820.o \
              r8180_gct.o \
              r8180_rtl8225.o \
              r8180_rtl8225z2.o \
              r8180_rtl8255.o

obj-$(CONFIG_REALTEK_PCI_RTL8185) += r8180.o

