#
# Makefile for the Realtek uncatalogued drivers.
#

obj-$(CONFIG_REALTEK_IR) += venus_ir.o
obj-$(CONFIG_REALTEK_VFD) += venus_vfd.o
obj-$(CONFIG_REALTEK_GPIO) += venus_gpio.o
obj-$(CONFIG_REALTEK_I2CSLAVE) += venus_i2cslave.o
obj-$(CONFIG_REALTEK_SE) += se.o
obj-$(CONFIG_REALTEK_WATCHPOINT) += venus_watch.o
obj-$(CONFIG_REALTEK_RPC) += RPC.o
RPC-objs := RPCDriver.o RPCintr.o RPCpoll.o
