


ieee80211-8187-objs            := ieee80211_softmac.o ieee80211_rx.o ieee80211_tx.o ieee80211_wx.o ieee80211_module.o ieee80211_softmac_wx.o

obj-$(CONFIG_REALTEK_USB_RTL8187)	+= ieee80211-8187.o ieee80211_crypt.o
obj-$(CONFIG_REALTEK_USB_RTL8187)	+= ieee80211_crypt_tkip.o ieee80211_crypt_ccmp.o ieee80211_crypt_wep.o
