#!/bin/sh
rm cmd/i386 -r
rm cmd/objchk_wxp_x86 -r
rm cmd/objfre_wxp_x86 -r
rm crypto/i386 -r
rm crypto/objchk_wxp_x86 -r
rm crypto/objfre_wxp_x86 -r
rm debug/i386 -r
rm debug/objchk_wxp_x86 -r
rm debug/objfre_wxp_x86 -r
rm eeprom/i386 -r
rm eeprom/objchk_wxp_x86 -r
rm eeprom/objfre_wxp_x86 -r
rm hal/RTL8711/i386 -r
rm hal/RTL8711/objchk_wxp_x86 -r
rm hal/RTL8711/objfre_wxp_x86 -r
rm io/i386 -r
rm io/objchk_wxp_x86 -r
rm io/objfre_wxp_x86 -r
rm ioctl/i386 -r
rm ioctl/objchk_wxp_x86 -r
rm ioctl/objfre_wxp_x86 -r
rm mlme/i386 -r
rm mlme/objchk_wxp_x86 -r
rm mlme/objfre_wxp_x86 -r
rm mp/i386 -r
rm mp/objchk_wxp_x86 -r
rm mp/objfre_wxp_x86 -r
rm os_dep/windows/xp/i386 -r
rm os_dep/windows/xp/objchk_wxp_x86 -r
rm os_dep/windows/xp/objfre_wxp_x86 -r
rm os_intf/windows/objchk_wxp_x86 -r
rm os_intf/windows/objfre_wxp_x86 -r
rm pwrctrl/i386 -r
rm pwrctrl/objchk_wxp_x86 -r
rm pwrctrl/objfre_wxp_x86 -r
rm recv/i386 -r
rm recv/objchk_wxp_x86 -r
rm recv/objfre_wxp_x86 -r
rm rf/i386 -r
rm rf/objchk_wxp_x86 -r
rm rf/objfre_wxp_x86 -r
rm xmit/i386 -r
rm xmit/objchk_wxp_x86 -r
rm xmit/objfre_wxp_x86 -r
rm sta_mgt/i386 -r
rm sta_mgt/objchk_wxp_x86 -r
rm sta_mgt/objfre_wxp_x86 -r
rm objchk_wxp_x86 -r
rm objfre_wxp_x86 -r
cp Makefile_linux_usb Makefile
make
