#Makefile for the linux ramfs routines.
#

#O_TARGET := ptpfs.o

obj-$(CONFIG_PTP_FS) += ptpfs.o
#obj-m := ptpfs.o
#obj-y := ptp_driver.o root.o ptp.o objects.o

ptpfs-y := ptp_driver.o root.o ptp.o objects.o

#obj-m += $(O_TARGET)
#obj-m := ptpfs.o

#obj-y := inode.o root.o ptp.o objects.o
#obj-m := $(O_TARGET)

#include $(TOPDIR)/Rules.make

