#ifndef __RTL8711_USB_REGDEF_H__
#define __RTL8711_USB_REGDEF_H__

#define VO_BULK_OUT_ENDPOINT_NUMBER				1
#define VI_BULK_OUT_ENDPOINT_NUMBER				2
#define BE_BULK_OUT_ENDPOINT_NUMBER				3
#define BK_BULK_OUT_ENDPOINT_NUMBER				4
#define TS_BULK_OUT_ENDPOINT_NUMBER				5
#define RX_BULK_IN_ENDPOINT_NUMBER				6
#define REG_INTERRUPT_OUT_ENDPOINT_NUMBER		7
#define REG_INTERRUPT_IN_ENDPOINT_NUMBER		8
#define TS_INTERRUPT_IN_ENDPOINT_NUMBER			9


#endif //__RTL8711_USB_REGDEF_H__


