#ifndef __RTL8711_EEPROM_REGDEF_H__
#define __RTL8711_EEPROM_REGDEF_H__

// EEPROM data locations
#define   EEPROM_SYSTEMCFG_OFFSET					0x02
#define	EEPROM_MAC_ADDRESS_OFFSET				0x03
#define	EEPROM_CHANNELPLAN_OFFSET				0x0F

#define	EEPROM_TXPOWERB1_OFFSET					0x11
#define	EEPROM_TXPOWERG1_OFFSET					0x15
#define	EEPROM_TXPOWER36_OFFSET					0x19

#ifdef CONFIG_USB_HCI
#define   EEPROM_COUNTRY_STRING_OFFSET			0x60
#define	EEPROM_TXPOWER149_OFFSET				0x63
#endif

#ifdef CONFIG_SDIO_HCI
#define   EEPROM_COUNTRY_STRING_OFFSET			0xB0
#define	EEPROM_TXPOWER149_OFFSET				0xB3
#define   EEPROM_SDIO_SETTING_OFFSET	0x2c
#define 	EEPROM_ORC_OFFSET			0x2d
#define 	EEPROM_CIS0_OFFSET			0x31
#define 	EEPROM_CIS1_OFFSET			0x42
#endif

#ifdef CONFIG_CFIO_HCI
#define   EEPROM_COUNTRY_STRING_OFFSET			0xF8
#define	EEPROM_TXPOWER149_OFFSET				0xFB
#endif



#endif
